<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZendExtensions\Module'                                         => __DIR__ . '/Module.php',
  'ZendExtensions\Service\ServiceException'                       => __DIR__ . '/src/ZendExtensions/Service/ServiceException.php',
  'ZendExtensions\View\Helper\HeadLink'                           => __DIR__ . '/src/ZendExtensions/View/Helper/HeadLink.php',
  'ZendExtensions\View\Helper\HeadScript'                         => __DIR__ . '/src/ZendExtensions/View/Helper/HeadScript.php',
  'ZendExtensions\View\Helper\InlineScript'                       => __DIR__ . '/src/ZendExtensions/View/Helper/InlineScript.php',
  'ZendExtensions\View\Model\JsendModel'                          => __DIR__ . '/src/ZendExtensions/View/Model/JsendModel.php',
  'ZendExtensions\Test\PHPUnit\AbstractRestfulControllerTestCase' => __DIR__ . '/src/ZendExtensions/Test/PHPUnit/AbstractRestfulControllerTestCase.php',
  'ZendExtensions\Test\PHPUnit\AbstractDatabaseTestCase'          => __DIR__ . '/src/ZendExtensions/Test/PHPUnit/AbstractDatabaseTestCase.php',
  'ZendExtensions\Navigation\Service\CustomNavigationFactory'     => __DIR__ . '/src/ZendExtensions/Navigation/Service/CustomNavigationFactory.php',
  'ZendExtensions\Model\Debug'                                    => __DIR__ . '/src/ZendExtensions/Model/Debug.php',
  'ZendExtensions\Entity\ServiceLocatorAwareEntity'               => __DIR__ . '/src/ZendExtensions/Entity/ServiceLocatorAwareEntity.php',
  'ZendExtensions\Entity\ServiceManagerListener'                  => __DIR__ . '/src/ZendExtensions/Entity/ServiceManagerListener.php',
  'ZendExtensions\Controller\AbstractRestfulJsendController'      => __DIR__ . '/src/ZendExtensions/Controller/AbstractRestfulJsendController.php',
  'ZendExtensions\Form\Form'                                      => __DIR__ . '/src/ZendExtensions/Form/Form.php',
);
