<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LandingPage\Module'                             => __DIR__ . '/Module.php',
  'LandingPageTest\Bootstrap'                      => __DIR__ . '/test/Bootstrap.php',
  'LandingPage\Controller\IndexController'         => __DIR__ . '/src/LandingPage/Controller/IndexController.php',
);
